export interface CredentialItem {
  id: string;
  title: string;
  category: "Drug License" | "Tax & Registration" | "Quality Standard" | "Trade Association";
  statusText: string;
  regNumberPlaceholder: string;
  issuingAuthority: string;
  validity: string;
  description: string;
  highlights: string[];
}

export interface BrandItem {
  name: string;
  tier: string;
  category: string;
  initials: string;
}

export interface ProductItem {
  id: string;
  name: string;
  genericName: string;
  category: "Generic" | "Surgical" | "Ayurvedic" | "OTC" | string;
  company: string;
  packSize: string;
  mrp: number;
  wholesalePrice: number;
  scheme?: string;
  batchNo: string;
  expDate: string;
  hsnCode: string;
  inStock: boolean;
  image: string;
  description: string;
}

export interface OfferSlide {
  id: string;
  occasion?: string;
  title: string;
  subtitle: string;
  highlight: string;
  code: string;
  badge: string;
  imageUrl: string;
  bgGradient?: string;
}

export interface ValuePropItem {
  title: string;
  tagline: string;
  description: string;
  iconName: string;
  metric: string;
  metricLabel: string;
}

export interface TimelineMilestone {
  year: string;
  phase: "Established" | "Growth" | "Expansion" | "Today";
  title: string;
  description: string;
  achievements: string[];
}

export interface BusinessDivision {
  id: "agency" | "store";
  slug: string;
  name: string;
  registeredHindiName: string;
  shortName: string;
  badge: string;
  tagline: string;
  heroHeadline: string;
  heroHighlight: string;
  description: string;
  targetAudience: string;
  focus: string[];
  brands: string[];
  categories: string[];
  primaryColor: string;
  accentColor: string;
  gradient: string;
  whatsappMessage: string;
  stats: { label: string; value: string }[];
}

export const DIVISIONS: { agency: BusinessDivision; store: BusinessDivision } = {
  agency: {
    id: "agency",
    slug: "/agency",
    name: "Saurav Medical Agency",
    registeredHindiName: "सौरव मेडिकल एजेंसी",
    shortName: "Agency (Surgical & Ethical)",
    badge: "Surgical & Ethical Supply",
    tagline: "Authorized Wholesale Distributor for Surgical Consumables, Hospital Supplies & Ethical Formulations",
    heroHeadline: "Surgical Disposables & Ethical Medicine Supply",
    heroHighlight: "Supplying multi-specialty hospitals, nursing homes, and clinics across Bhagalpur and East Bihar with 100% genuine surgical consumables and ethical medicines at direct depot rates.",
    description: "Saurav Medical Agency specializes in institutional hospital procurement, surgical disposables, OT consumables, life-saving critical care injectables, and ethical medicines from leading pharmaceutical manufacturers.",
    targetAudience: "Hospitals, Nursing Homes, Surgeons, Specialty Clinics & Licensed Retail Chemists",
    focus: [
      "Sterile Surgical Disposables (Syringes, Infusion Sets, Cannula, Gloves)",
      "Ethical Prescription Formulations & Critical Care Injectables",
      "Direct Hospital & Nursing Home Rate Contracts with Priority Delivery",
      "Cold-Chain Assured Storage (2°C – 8°C) & 24/7 Emergency OT Dispatch",
      "100% Computerized B2B Tax Invoices with Full Input Tax Credit (ITC)",
    ],
    brands: ["Safeone", "Cipla", "Sun Pharma", "Alkem", "Abbott", "Biochem", "Lupin", "Dr Reddy", "Alembic", "BD", "Aristo"],
    categories: ["Surgical Disposables", "Ethical Formulations", "Critical Care & Injections", "Hospital Consumables", "Wound & Ortho Care"],
    primaryColor: "#0b1e36",
    accentColor: "#2563eb",
    gradient: "from-[#0b1e36] via-[#123158] to-[#1d4ed8]",
    whatsappMessage: "Hello Saurav Medical Agency, I am representing a Hospital / Clinic / Medical Store and want to enquire about Surgical & Ethical medicine wholesale supply.",
    stats: [
      { label: "Authorized Depots", value: "15+" },
      { label: "Hospitals & Clinics", value: "120+" },
      { label: "Surgical SKUs", value: "800+" },
      { label: "Emergency OT Dispatch", value: "24/7" },
    ],
  },
  store: {
    id: "store",
    slug: "/store",
    name: "Saurav Medical Store Agency",
    registeredHindiName: "सौरव मेडिकल स्टोर एजेंसी",
    shortName: "Store (Generic Wholesale)",
    badge: "Generic Medicine Wholesale",
    tagline: "Empowering Retail Pharmacies with Fast-Moving Generic Medicines & Highest Profit Margins",
    heroHeadline: "High-Margin Generic Medicines for Retail Pharmacies",
    heroHighlight: "Delivering fast-moving generic formulations, unbeatable wholesale PTR rates, continuous 10+1 free schemes, and reliable same-day stock replenishment directly to chemist counters.",
    description: "Saurav Medical Store Agency is the preferred generic medicine distribution partner for 500+ chemist shops and pharmacies across Bhagalpur, offering the highest trade margins and honest wholesale prices.",
    targetAudience: "Retail Medical Stores, Community Pharmacies, Rural Dispensaries & Chemists",
    focus: [
      "High-Demand Generic Molecules (Antibiotics, Analgesics, PPIs, Gastro)",
      "Continuous 10+1 Free Schemes & Seasonal Slabs on Fast-Moving Lots",
      "Maximum Retailer Profitability (35% – 60% Margin) & Honest PTR Rates",
      "Pediatric & Adult Cough Syrups, Suspensions, Drops & Ointments",
      "Same-Day Counter Dispatch & Free Local Delivery for Chemists",
    ],
    brands: ["Smart Lab", "Silver Cross", "Laborate", "Windlass", "Lee Ford", "Touchone", "Mankind", "Alkem Generics", "Torque", "Ramsans"],
    categories: ["Antibiotics & Anti-Infectives", "Analgesics & Pain Relief", "Gastro & Antacids", "Cough & Cold Syrups", "Vitamins & Nutritional", "OTC Care"],
    primaryColor: "#0284c7",
    accentColor: "#38bdf8",
    gradient: "from-[#0369a1] via-[#0284c7] to-[#0ea5e9]",
    whatsappMessage: "Hello Saurav Medical Store Agency, I am a Chemist / Medical Store owner and want to enquire about Generic medicines stock and current 10+1 schemes.",
    stats: [
      { label: "Active Retail Chemists", value: "500+" },
      { label: "Ready Generic SKUs", value: "1,500+" },
      { label: "Average Chemist Margin", value: "35%–60%" },
      { label: "Same-Day Delivery", value: "Guaranteed" },
    ],
  },
};

export const COMPANY_DETAILS = {
  name: "Saurav Medical",
  registeredParentName: "Saurav Medical Group",
  division1: "Saurav Medical Agency",
  division2: "Saurav Medical Store Agency",
  tagline: "Surgical, Ethical & Generic Healthcare Distribution Since 2004",
  ownerName: "Santosh Kumar",
  role: "Proprietor & Managing Director",
  ownerPhotoUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=80",
  mobile: "7070605245",
  phoneDisplay: "+91 7070605245",
  whatsappUrl: "https://wa.me/917070605245?text=Hello%20Saurav%20Medical,%20I%20want%20to%20enquire%20about%20wholesale%20supply.",
  whatsappAgencyUrl: "https://wa.me/917070605245?text=Hello%20Saurav%20Medical%20Agency,%20I%20am%20enquiring%20about%20Surgical%20%26%20Ethical%20medicine%20supply.",
  whatsappStoreUrl: "https://wa.me/917070605245?text=Hello%20Saurav%20Medical%20Store%20Agency,%20I%20am%20enquiring%20about%20Generic%20medicines%20and%2010%2B1%20schemes.",
  upiId: "eazypay.589015203@icici",
  qrImageUrl: "/payment-qr.png",
  address: "Kotwali Chowk, Beside ICICI Bank (1st Floor), Bhagalpur - 812002 (Bihar)",
  city: "Bhagalpur",
  state: "Bihar",
  pincode: "812002",
  email: "wholesale@sauravmedical.com",
  hours: "Mon – Sat: 9:00 AM – 8:30 PM (Emergency OT Dispatch 24/7 on Call)",
  dlPlaceholder: "DL Nos. 20B/BGP/XXXX & 21B/BGP/XXXX (Form 20B & 21B)",
  gstinPlaceholder: "GSTIN: 10AXXXX0000X1ZX (Wholesale Taxpayer)",
};

// 21 Partner Companies from Visiting Card Back
export const CARD_COMPANIES: BrandItem[] = [
  { name: "Alkem", tier: "Direct Depot", category: "Antibiotics & Generics", initials: "AK" },
  { name: "Aristo", tier: "Authorized Wholesale", category: "Gastro & Anti-Infectives", initials: "AR" },
  { name: "Cipla", tier: "Direct Wholesale", category: "Respiratory & Critical Care", initials: "CP" },
  { name: "Medley", tier: "Authorized Wholesale", category: "Analgesics & Hematinics", initials: "MD" },
  { name: "Lupin", tier: "Direct Wholesale", category: "Cardiology & Anti-TB", initials: "LP" },
  { name: "Abbott", tier: "Super-Stockist", category: "Metabolic & Nutrition", initials: "AB" },
  { name: "Intas", tier: "Authorized Wholesale", category: "CNS & Critical Care", initials: "IN" },
  { name: "Smart Lab", tier: "Generic Line", category: "Daily Acute Generics", initials: "SL" },
  { name: "Silver Cross", tier: "Generic Line", category: "Essential Formulations", initials: "SC" },
  { name: "Biochem", tier: "Authorized Wholesale", category: "Injectables & Antibiotics", initials: "BC" },
  { name: "Torque", tier: "Wholesale Partner", category: "Syrups, Ointments & Derma", initials: "TQ" },
  { name: "Jacsonpal", tier: "Authorized Depot", category: "Gynecology & Pain Care", initials: "JP" },
  { name: "Windlass", tier: "Generic Line", category: "Quality Formulations", initials: "WL" },
  { name: "Mankind", tier: "Super-Stockist", category: "OTC, Antibiotics & Derma", initials: "MK" },
  { name: "Laborate", tier: "Generic Line", category: "Affordable Generic Tablets", initials: "LB" },
  { name: "Lee Ford", tier: "Wholesale Partner", category: "Nutraceuticals & Pain Care", initials: "LF" },
  { name: "Ramsans", tier: "Authorized Wholesale", category: "Essential Healthcare", initials: "RS" },
  { name: "Safeone", tier: "Surgical & Health", category: "Sterile Surgical Disposables", initials: "SO" },
  { name: "Touchone", tier: "Generic Line", category: "General Formulations", initials: "TO" },
  { name: "Dr Reddy", tier: "Super-Stockist", category: "Gastro & Chronic Therapies", initials: "DR" },
  { name: "Alembic", tier: "Direct Wholesale", category: "Anti-Infectives & Cardiology", initials: "AL" },
];

export const OFFER_SLIDES: OfferSlide[] = [
  {
    id: "offer-1",
    occasion: "Festival Special Scheme",
    title: "Diwali & Festive Medicine Offers",
    subtitle: "Special wholesale rates on high-demand antibiotics and general medicines for local pharmacies",
    highlight: "10 + 1 Free on Antibiotics + 5% Extra Cash Discount on Bulk Lots",
    code: "SCHEME-FESTIVE",
    badge: "Festival Special",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    bgGradient: "from-[#0b1e36] via-[#102a4c] to-[#0f766e]",
  },
  {
    id: "offer-2",
    occasion: "Seasonal Monsoon Scheme",
    title: "Monsoon Healthcare Ready Stock",
    subtitle: "Fast-moving Paracetamol, Cefixime, Azithromycin and cough syrups in ready stock",
    highlight: "10 + 1 Free Scheme + Extra 3% Slab Discount on Full Box Orders",
    code: "SCHEME-10+1",
    badge: "Seasonal Offer",
    imageUrl: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=1200&q=80",
    bgGradient: "from-[#0f766e] via-[#115e59] to-[#0b1e36]",
  },
  {
    id: "offer-3",
    occasion: "Hospital & Clinic Bulk Supply",
    title: "Surgical Disposables & Consumables",
    subtitle: "Bulk cartons of Safeone syringes, IV sets, examination gloves, and surgical cotton",
    highlight: "Flat 18% Wholesale Margin on Carton Packing | Ready for Delivery",
    code: "SURGICAL-CARTON",
    badge: "Bulk Carton Deal",
    imageUrl: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=1200&q=80",
    bgGradient: "from-[#1e293b] via-[#0b1e36] to-[#0369a1]",
  },
];

export const DUMMY_PRODUCTS: ProductItem[] = [
  {
    id: "prod-1",
    name: "Cefixime 200mg Tablets",
    genericName: "Cefixime Dispersible 200mg",
    category: "Generic",
    company: "Alkem",
    packSize: "10 x 10 Strips / Box",
    mrp: 1450,
    wholesalePrice: 480,
    scheme: "10 + 1 Free",
    batchNo: "AK-CF241",
    expDate: "11/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Third-generation cephalosporin broad-spectrum antibiotic formulation for respiratory and UTI treatment.",
  },
  {
    id: "prod-2",
    name: "Pantoprazole & Domperidone SR",
    genericName: "Pantoprazole 40mg + Domperidone 30mg SR",
    category: "Generic",
    company: "Aristo",
    packSize: "10 x 10 ALU-ALU Strips",
    mrp: 1280,
    wholesalePrice: 395,
    scheme: "Regular Wholesale",
    batchNo: "AR-PD902",
    expDate: "08/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Sustained-release antacid and anti-emetic gastro capsules for GERD and acidity management.",
  },
  {
    id: "prod-3",
    name: "Paracetamol 650mg Fast Action",
    genericName: "Paracetamol IP 650mg",
    category: "Generic",
    company: "Cipla",
    packSize: "20 x 15 Tablets Blister",
    mrp: 420,
    wholesalePrice: 190,
    scheme: "20 + 2 Free",
    batchNo: "CP-PC441",
    expDate: "03/2028",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "High-efficacy analgesic and antipyretic formulation for fever and chronic body pain relief.",
  },
  {
    id: "prod-4",
    name: "Amoxycillin & Pot. Clavulanate 625",
    genericName: "Amoxicillin 500mg + Clavulanic Acid 125mg",
    category: "Generic",
    company: "Mankind",
    packSize: "10 x 1 x 6 Strips Pack",
    mrp: 1650,
    wholesalePrice: 620,
    scheme: "Special Slab Rate",
    batchNo: "MK-CV810",
    expDate: "01/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Beta-lactamase inhibitor combination antibiotic for dental, skin, and lower respiratory infections.",
  },
  {
    id: "prod-5",
    name: "Omeprazole 20mg Hard Capsules",
    genericName: "Omeprazole IP 20mg",
    category: "Generic",
    company: "Dr Reddy",
    packSize: "10 x 20 Strip Pack",
    mrp: 890,
    wholesalePrice: 280,
    scheme: "10 + 1 Free",
    batchNo: "DR-OM312",
    expDate: "09/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Enteric-coated proton pump inhibitor for gastric ulcers, hyperacidity, and heartburn.",
  },
  {
    id: "prod-6",
    name: "Azithromycin 500mg Tablets",
    genericName: "Azithromycin IP 500mg",
    category: "Generic",
    company: "Lupin",
    packSize: "10 x 3 Blister Pack",
    mrp: 1190,
    wholesalePrice: 410,
    scheme: "Bulk Rate",
    batchNo: "LP-AZ550",
    expDate: "06/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "Broad-spectrum macrolide antibiotic for acute ENT and respiratory tract infections.",
  },
  {
    id: "prod-7",
    name: "Disposable Sterile Syringes 5ml with Needle",
    genericName: "Single-use 5ml Luer Lock Syringe 23G",
    category: "Surgical",
    company: "Safeone",
    packSize: "Box of 100 Pcs",
    mrp: 650,
    wholesalePrice: 290,
    scheme: "Carton Rate Available",
    batchNo: "SO-SY501",
    expDate: "12/2029",
    hsnCode: "9018",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80",
    description: "EO sterilized medical-grade single-use syringe with ultra-fine siliconized stainless steel needle.",
  },
  {
    id: "prod-8",
    name: "IV Infusion Set with Air Vent & Filter",
    genericName: "Sterile Gravity IV Infusion Tubing Set",
    category: "Surgical",
    company: "Safeone",
    packSize: "Pack of 50 Sets",
    mrp: 850,
    wholesalePrice: 360,
    scheme: "Hospital Bulk Tier",
    batchNo: "SO-IV112",
    expDate: "10/2028",
    hsnCode: "9018",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80",
    description: "Kink-resistant medical PVC IV line equipped with 15-micron fluid filter and hydrophobic air venting.",
  },
  {
    id: "prod-9",
    name: "Latex Examination Gloves (Powder-Free)",
    genericName: "Non-sterile Powder-Free Examination Gloves - Medium",
    category: "Surgical",
    company: "Safeone",
    packSize: "Box of 100 Pcs (50 Pairs)",
    mrp: 550,
    wholesalePrice: 240,
    scheme: "10 Boxes Lot Offer",
    batchNo: "SO-GL780",
    expDate: "05/2029",
    hsnCode: "4015",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80",
    description: "Micro-textured natural rubber latex gloves offering high tactile sensitivity and tear resistance.",
  },
  {
    id: "prod-10",
    name: "Hospital Grade Absorbent Cotton 500g",
    genericName: "IP Pure Bleached Surgical Cotton Roll",
    category: "Surgical",
    company: "Safeone",
    packSize: "Bundle of 5 Rolls (500g each)",
    mrp: 750,
    wholesalePrice: 380,
    scheme: "Regular Wholesale",
    batchNo: "SO-CT309",
    expDate: "N/A",
    hsnCode: "3005",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80",
    description: "100% pure bleached surgical absorbent cotton for clinical wound dressings and antiseptic swabbing.",
  },
  {
    id: "prod-11",
    name: "Herbal Bronchial Cough Relief Syrup",
    genericName: "Tulsi, Vasaka, Mulethi & Kantkari Ayurvedic Blend",
    category: "Ayurvedic",
    company: "Torque",
    packSize: "Pack of 12 Bottles (100ml each)",
    mrp: 1320,
    wholesalePrice: 580,
    scheme: "12 + 2 Free",
    batchNo: "TQ-HC101",
    expDate: "04/2027",
    hsnCode: "3003",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Non-drowsy herbal expectorant syrup for soothing throat irritation and bronchial chest congestion.",
  },
  {
    id: "prod-12",
    name: "Ayurvedic Joint Pain Liniment Oil",
    genericName: "Mahanarayan, Gandhapura & Nilgiri Medicated Oil",
    category: "Ayurvedic",
    company: "Lee Ford",
    packSize: "Pack of 10 Bottles (60ml each)",
    mrp: 1450,
    wholesalePrice: 590,
    scheme: "10 + 1 Free",
    batchNo: "LF-JO220",
    expDate: "09/2027",
    hsnCode: "3003",
    inStock: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Fast-absorbing traditional herbal formulation for muscular stiffness, joint inflammation, and sprains.",
  },
  {
    id: "prod-13",
    name: "Multi-Vitamin & Zinc Energy Tonic",
    genericName: "B-Complex + L-Lysine + Zinc Multi-Nutrient Syrup",
    category: "OTC",
    company: "Mankind",
    packSize: "Shipper of 24 Bottles (200ml each)",
    mrp: 3600,
    wholesalePrice: 1450,
    scheme: "Shipper Bulk Pack",
    batchNo: "MK-VT890",
    expDate: "07/2027",
    hsnCode: "2106",
    inStock: true,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "High-turnover daily OTC nutritional tonic supporting immune defense, energy, and convalescence.",
  },
  {
    id: "prod-14",
    name: "Digestive Enzyme & Carminative Drops",
    genericName: "Fungal Diastase + Pepsin Liquid Enzyme",
    category: "OTC",
    company: "Aristo",
    packSize: "Pack of 20 Bottles (30ml drops)",
    mrp: 1200,
    wholesalePrice: 480,
    scheme: "20 + 2 Free",
    batchNo: "AR-EN404",
    expDate: "11/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Enzymatic drops for indigestion, bloating, gastrointestinal distress, and appetite stimulation.",
  },
  {
    id: "prod-15",
    name: "Diclofenac & Linseed Analgesic Gel",
    genericName: "Diclofenac Diethylamine + Virgin Linseed Oil + Methyl Salicylate",
    category: "OTC",
    company: "Laborate",
    packSize: "Pack of 20 Tubes (30g each)",
    mrp: 1500,
    wholesalePrice: 490,
    scheme: "Counter Display Box",
    batchNo: "LB-DG662",
    expDate: "05/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Fast-acting topical anti-inflammatory gel for lumbar pain, neck stiffness, and sprains.",
  },
  {
    id: "prod-16",
    name: "Cetirizine 10mg Anti-Allergic Tablets",
    genericName: "Cetirizine Dihydrochloride IP 10mg",
    category: "Generic",
    company: "Smart Lab",
    packSize: "20 x 10 Tablets Strip Box",
    mrp: 480,
    wholesalePrice: 160,
    scheme: "20 + 4 Free",
    batchNo: "SL-CT109",
    expDate: "12/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "High-volume generic second-generation anti-histamine for allergic rhinitis, watery eyes, and hives.",
  },
];

export const SURGICAL_ETHICAL_PRODUCTS: ProductItem[] = [
  {
    id: "surg-1",
    name: "Safeone Sterile Disposable Syringes 5ml",
    genericName: "Sterile Hypodermic Syringe with Needle 24G",
    category: "Surgical Disposables",
    company: "Safeone",
    packSize: "Box of 100 Pieces",
    mrp: 950,
    wholesalePrice: 420,
    scheme: "Bulk Carton Rate Available",
    batchNo: "SO-SY502",
    expDate: "09/2028",
    hsnCode: "9018",
    inStock: true,
    image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-clear medical-grade polypropylene barrel with smooth elastomer piston and blister sterile packing for hospitals and clinics.",
  },
  {
    id: "surg-2",
    name: "Safeone IV Infusion Set with Air Vent",
    genericName: "Sterile Intravenous Infusion Set (Non-Toxic, Pyrogen-Free)",
    category: "Surgical Disposables",
    company: "Safeone",
    packSize: "Carton of 250 Units (Individually Packed)",
    mrp: 1850,
    wholesalePrice: 850,
    scheme: "Hospital Lot Deal",
    batchNo: "SO-IV119",
    expDate: "12/2028",
    hsnCode: "9018",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=600&q=80",
    description: "Sharp spike with integrated 15-micron fluid filter, flexible drip chamber, and smooth kink-resistant tubing for hospital OT and wards.",
  },
  {
    id: "surg-3",
    name: "Safeone Nitrile Examination Sterile Gloves",
    genericName: "Medical Grade Nitrile Gloves Powder-Free",
    category: "Surgical Disposables",
    company: "Safeone",
    packSize: "Box of 50 Pairs (100 Gloves)",
    mrp: 850,
    wholesalePrice: 380,
    scheme: "Carton Rate @ ₹340",
    batchNo: "SO-GL882",
    expDate: "06/2028",
    hsnCode: "4015",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=600&q=80",
    description: "Textured fingertips, high tactile sensitivity, puncture resistant, ideal for operating theatres and pathology laboratories.",
  },
  {
    id: "surg-4",
    name: "Safeone IV Cannula with Injection Port & Wings",
    genericName: "Sterile Teflon IV Cannula (18G / 20G / 22G / 24G)",
    category: "Surgical Disposables",
    company: "Safeone",
    packSize: "Box of 50 Pieces (Color Coded)",
    mrp: 1450,
    wholesalePrice: 650,
    scheme: "Hospital Tier Price",
    batchNo: "SO-CN412",
    expDate: "10/2028",
    hsnCode: "9018",
    inStock: true,
    image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=600&q=80",
    description: "FEP radiopaque catheter with back-cut needle bevel for painless venipuncture in hospital emergency and intensive care units.",
  },
  {
    id: "surg-5",
    name: "Safeone Absorbent Surgical Cotton Wool (500g)",
    genericName: "Pure Absorbent Cotton Wool IP Roll",
    category: "Hospital Consumables",
    company: "Safeone",
    packSize: "500g Roll (Hermetically Sealed)",
    mrp: 280,
    wholesalePrice: 140,
    scheme: "Carton of 20 Rolls",
    batchNo: "SO-CT901",
    expDate: "11/2029",
    hsnCode: "5201",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "100% natural, bleached, odorless, high-absorbency cotton wool for wound dressing, surgical cleansing, and hospital swabs.",
  },
  {
    id: "eth-1",
    name: "Augmentin 625 Duo Tablets",
    genericName: "Amoxicillin 500mg + Clavulanic Acid 125mg (Ethical Rx)",
    category: "Ethical Formulations",
    company: "Abbott",
    packSize: "10 x 10 Strips Box",
    mrp: 2050,
    wholesalePrice: 1380,
    scheme: "Direct Depot Rate",
    batchNo: "AB-AG625",
    expDate: "04/2028",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Gold-standard ethical prescription co-amoxiclav indicated for severe respiratory, skin, and post-operative surgical infections.",
  },
  {
    id: "eth-2",
    name: "Monocef 1g Sterile IV/IM Injection",
    genericName: "Ceftriaxone Sodium Sterile Powder for Injection 1000mg",
    category: "Critical Care & Injections",
    company: "Aristo",
    packSize: "Pack of 10 Vials with Water for Injection",
    mrp: 650,
    wholesalePrice: 395,
    scheme: "Hospital Box Rate",
    batchNo: "AR-MC102",
    expDate: "08/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=80",
    description: "Essential ethical antibiotic injection for hospital inpatient management of bacterial meningitis, septicemia, and peri-operative prophylaxis.",
  },
  {
    id: "eth-3",
    name: "Pantocid 40mg IV Sterile Injection",
    genericName: "Pantoprazole Sodium for Injection 40mg (Vial)",
    category: "Critical Care & Injections",
    company: "Sun Pharma",
    packSize: "Box of 10 Vials",
    mrp: 580,
    wholesalePrice: 340,
    scheme: "Institutional Bulk",
    batchNo: "SP-PC440",
    expDate: "10/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Ethical proton-pump inhibitor injection for acute upper GI bleeding and prophylaxis against stress ulceration in ICU patients.",
  },
  {
    id: "eth-4",
    name: "Budecort 0.5mg Respules (Inhalation)",
    genericName: "Budesonide Inhalation Suspension 0.5mg / 2ml",
    category: "Ethical Formulations",
    company: "Cipla",
    packSize: "Pack of 20 Respules (4 x 5 strips)",
    mrp: 620,
    wholesalePrice: 430,
    scheme: "Direct Stockist Rate",
    batchNo: "CP-BC220",
    expDate: "07/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "High-demand ethical corticosteroid inhalation respules for acute asthma exacerbations, croup, and COPD hospital nebulization.",
  },
  {
    id: "eth-5",
    name: "Meropenem 1g Sterile ICU Injection",
    genericName: "Meropenem Trihydrate with Sodium Carbonate 1000mg",
    category: "Critical Care & Injections",
    company: "Alkem",
    packSize: "Single Sterile Glass Vial with Solvent",
    mrp: 1450,
    wholesalePrice: 680,
    scheme: "ICU Emergency Supply",
    batchNo: "AK-MP901",
    expDate: "05/2028",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-broad-spectrum carbapenem intravenous antibiotic for life-threatening nosocomial pneumonia, intra-abdominal, and ICU infections.",
  },
  {
    id: "eth-6",
    name: "Dynapar AQ 1ml Injection",
    genericName: "Diclofenac Sodium 75mg / 1ml Painless Injection",
    category: "Critical Care & Injections",
    company: "Biochem",
    packSize: "Box of 10 Ampoules x 1ml",
    mrp: 320,
    wholesalePrice: 195,
    scheme: "Hospital Lot Deal",
    batchNo: "BC-DN110",
    expDate: "09/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Proprietary aqueous painless formula for acute post-operative surgical analgesia, renal colic, and severe orthopedic trauma pain.",
  },
  {
    id: "surg-6",
    name: "Safeone Sterile Waterproof Wound Dressing Pad",
    genericName: "Polyurethane Film Dressing with Absorbent Central Pad (10cm x 10cm)",
    category: "Wound & Ortho Care",
    company: "Safeone",
    packSize: "Box of 25 Individually Sterile Pouches",
    mrp: 750,
    wholesalePrice: 320,
    scheme: "OT Box Price",
    batchNo: "SO-WD550",
    expDate: "12/2028",
    hsnCode: "3005",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=600&q=80",
    description: "Sterile transparent adhesive border with central non-adherent pad, keeps surgical incisions completely dry during patient recovery.",
  },
];

export const GENERIC_PRODUCTS: ProductItem[] = [
  {
    id: "gen-1",
    name: "Cefixime 200mg Dispersible Tablets",
    genericName: "Cefixime IP 200mg",
    category: "Antibiotics & Anti-Infectives",
    company: "Alkem Generics",
    packSize: "10 x 10 ALU-ALU Strips Box",
    mrp: 1450,
    wholesalePrice: 440,
    scheme: "10 + 1 Free Scheme",
    batchNo: "AK-CF202",
    expDate: "11/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Third-generation cephalosporin broad-spectrum antibiotic formulation, highest selling formulation for retail medical stores.",
  },
  {
    id: "gen-2",
    name: "Paracetamol 650mg Fast Action Tablets",
    genericName: "Paracetamol IP 650mg",
    category: "Analgesics & Pain Relief",
    company: "Smart Lab",
    packSize: "20 x 15 Tablets Blister Box",
    mrp: 420,
    wholesalePrice: 175,
    scheme: "20 + 3 Free Scheme",
    batchNo: "SL-PC650",
    expDate: "03/2028",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "Fast-dissolving anti-pyretic formulation for viral fever, headaches, body ache, and seasonal cold treatment.",
  },
  {
    id: "gen-3",
    name: "Pantoprazole 40mg + Domperidone 30mg SR",
    genericName: "Pantoprazole Sodium 40mg + Domperidone 30mg SR Capsules",
    category: "Gastro & Antacids",
    company: "Silver Cross",
    packSize: "10 x 10 ALU-ALU Strips",
    mrp: 1250,
    wholesalePrice: 360,
    scheme: "10 + 1 Free Scheme",
    batchNo: "SC-PD402",
    expDate: "08/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "High-margin sustained release gastro-prokinetic capsules, heavy daily demand in community chemist shops.",
  },
  {
    id: "gen-4",
    name: "Azithromycin 500mg Tablets",
    genericName: "Azithromycin Dihydrate IP 500mg",
    category: "Antibiotics & Anti-Infectives",
    company: "Laborate",
    packSize: "10 x 3 Tablets Blister Box",
    mrp: 850,
    wholesalePrice: 280,
    scheme: "10 + 1 Free Scheme",
    batchNo: "LB-AZ500",
    expDate: "09/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Macrolide antibiotic 3-day treatment formulation for throat infection, tonsillitis, chest infections, and broncho-pneumonia.",
  },
  {
    id: "gen-5",
    name: "Amoxicillin 500mg Capsules",
    genericName: "Amoxicillin Trihydrate IP 500mg",
    category: "Antibiotics & Anti-Infectives",
    company: "Windlass",
    packSize: "10 x 10 Capsules Blister Pack",
    mrp: 980,
    wholesalePrice: 340,
    scheme: "10 + 1 Free Scheme",
    batchNo: "WL-AM500",
    expDate: "10/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Essential penicillins group broad-spectrum antibiotic capsule, high turnover in rural and semi-urban medical dispensaries.",
  },
  {
    id: "gen-6",
    name: "Levocetirizine 5mg + Montelukast 10mg",
    genericName: "Montelukast Sodium 10mg + Levocetirizine HCl 5mg",
    category: "Allergy & Respiratory",
    company: "Lee Ford",
    packSize: "10 x 10 ALU-ALU Strips",
    mrp: 1350,
    wholesalePrice: 390,
    scheme: "10 + 2 Free Scheme",
    batchNo: "LF-LM105",
    expDate: "04/2028",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "Dual action anti-allergic and leukotriene receptor antagonist for chronic allergic asthma, dust allergy, and night cough.",
  },
  {
    id: "gen-7",
    name: "Ambroxol + Levosalbutamol + Guaiphenesin Syrup",
    genericName: "Bronchodilator Expectorant Mucolytic Syrup 100ml",
    category: "Cough & Cold Syrups",
    company: "Torque",
    packSize: "Carton of 24 Bottles (100ml PET Bottle)",
    mrp: 2400,
    wholesalePrice: 840,
    scheme: "12 + 2 Free Scheme",
    batchNo: "TQ-CS100",
    expDate: "06/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=600&q=80",
    description: "Fast-acting productive cough formula, thins mucus and dilates airways, high seasonal winter/monsoon demand.",
  },
  {
    id: "gen-8",
    name: "Multivitamin with L-Lysine & Zinc Syrup (200ml)",
    genericName: "Health Tonic & Appetite Stimulant Syrup",
    category: "Vitamins & Nutritional",
    company: "Ramsans",
    packSize: "Box of 20 Bottles x 200ml",
    mrp: 2900,
    wholesalePrice: 960,
    scheme: "10 + 1 Free Scheme",
    batchNo: "RS-VT200",
    expDate: "01/2028",
    hsnCode: "2106",
    inStock: true,
    image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=600&q=80",
    description: "Comprehensive multivitamin with zinc and amino acid lysine for convalescence, fatigue recovery, and immunity boost.",
  },
  {
    id: "gen-9",
    name: "Diclofenac Sodium + Linseed Oil Gel (30g)",
    genericName: "Diclofenac Diethylamine 1.16% + Virgin Linseed Oil Topical Gel",
    category: "Analgesics & Pain Relief",
    company: "Laborate",
    packSize: "Box of 20 Tubes x 30g Lami-tube",
    mrp: 1700,
    wholesalePrice: 490,
    scheme: "10 + 2 Free Scheme",
    batchNo: "LB-DG662",
    expDate: "05/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Fast-absorbing anti-inflammatory pain gel for knee joint pain, sciatica, muscle sprains, and backache.",
  },
  {
    id: "gen-10",
    name: "Ofloxacin 200mg + Ornidazole 500mg Tablets",
    genericName: "Ofloxacin 200mg + Ornidazole 500mg IP",
    category: "Antibiotics & Anti-Infectives",
    company: "Smart Lab",
    packSize: "10 x 10 Strips Box",
    mrp: 1250,
    wholesalePrice: 380,
    scheme: "10 + 1 Free Scheme",
    batchNo: "SL-OO250",
    expDate: "11/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Proven dual antibiotic-antiprotozoal formulation for acute gastroenteritis, dysentery, bacterial diarrhea, and dental infections.",
  },
  {
    id: "gen-11",
    name: "Calcium Carbonate 500mg + Vitamin D3 Tablets",
    genericName: "Elemental Calcium 500mg + Cholecalciferol 250 IU",
    category: "Vitamins & Nutritional",
    company: "Touchone",
    packSize: "15 x 10 Tablets Blister Box",
    mrp: 1100,
    wholesalePrice: 310,
    scheme: "10 + 1 Free Scheme",
    batchNo: "TO-CL500",
    expDate: "09/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    description: "Daily bone health, osteoporosis prevention, and post-menopausal calcium supplement with high patient compliance.",
  },
  {
    id: "gen-12",
    name: "Rabeprazole 20mg + Domperidone 30mg DSR",
    genericName: "Rabeprazole Sodium 20mg + Domperidone 30mg SR",
    category: "Gastro & Antacids",
    company: "Silver Cross",
    packSize: "10 x 10 ALU-ALU Strips",
    mrp: 1320,
    wholesalePrice: 380,
    scheme: "10 + 1 Free Scheme",
    batchNo: "SC-RD203",
    expDate: "08/2027",
    hsnCode: "3004",
    inStock: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Fast-acting proton pump inhibitor formulation for persistent nocturnal acid reflux, dyspepsia, and nausea.",
  },
];

export const CREDENTIALS_DATA: CredentialItem[] = [
  {
    id: "dl-20b-21b",
    title: "Wholesale Drug License (Form 20-B & 21-B)",
    category: "Drug License",
    statusText: "Active & Verified",
    regNumberPlaceholder: "DL No. 20B/BGP/XXXX & 21B/BGP/XXXX",
    issuingAuthority: "Drugs Control Directorate, Bihar",
    validity: "Active Wholesale License",
    description: "Official wholesale license under the Drugs & Cosmetics Act to store and distribute allopathic medicines and healthcare products to medical stores.",
    highlights: [
      "Authorized wholesale counter at Kotwali Chowk, Bhagalpur",
      "Full compliance with government medicine distribution rules",
      "Qualified pharmacist on premise during business hours",
    ],
  },
  {
    id: "gstin-reg",
    title: "Goods & Services Tax Registration (GSTIN)",
    category: "Tax & Registration",
    statusText: "Regular GST Taxpayer",
    regNumberPlaceholder: "GSTIN: 10XXXXX0000X1ZX",
    issuingAuthority: "Commercial Taxes Department, Bihar",
    validity: "Active & Verified",
    description: "100% genuine computerized tax bills with HSN codes so your medical store can easily claim input tax credit (ITC).",
    highlights: [
      "Itemized B2B bills with proper HSN 3004 & 9018 codes",
      "Prompt monthly GST filing for fast tax credit claims",
      "Complete batch number and expiry date on every bill",
    ],
  },
  {
    id: "bhagalpur-chemists",
    title: "Bhagalpur Chemists & Druggists Association",
    category: "Trade Association",
    statusText: "Life Member",
    regNumberPlaceholder: "BDCDA / MBR / BGP-XXXX",
    issuingAuthority: "Bihar Chemists & Druggists Association (BCDA)",
    validity: "Permanent Life Member",
    description: "Active member of local and state chemist associations, maintaining ethical wholesale prices, fair margins, and reliable medicine supply.",
    highlights: [
      "Follows fair trade guidelines for medical stores",
      "Close relationship with community pharmacies across Bhagalpur",
      "Full manufacturer support on returns and damages",
    ],
  },
  {
    id: "gdp-storage",
    title: "Safe Medicine Storage & Quality Check",
    category: "Quality Standard",
    statusText: "Audited Warehouse",
    regNumberPlaceholder: "GDP-QA / BGP-2026",
    issuingAuthority: "Standard Pharma Storage Protocol",
    validity: "Regularly Verified",
    description: "Clean, temperature-controlled warehouse in Kotwali Chowk with dedicated refrigerators and systematic stock rotation (FEFO).",
    highlights: [
      "Dedicated 2°C – 8°C refrigerators for insulin and vaccines",
      "Zero counterfeit tolerance — 100% direct company supply",
      "Safe box packing for glass ampoules, syrups, and vials",
    ],
  },
];

export const VALUE_PROPOSITIONS: ValuePropItem[] = [
  {
    title: "100% Genuine Medicines",
    tagline: "Direct Company Supply",
    description: "We source all medicines directly from authorized company depots with batch test reports. Zero tolerance for fake or low-quality stock.",
    iconName: "ShieldCheck",
    metric: "100%",
    metricLabel: "Original",
  },
  {
    title: "Safe Cold Storage (2°C – 8°C)",
    tagline: "Protects Sensitive Medicines",
    description: "Dedicated medical refrigerators for insulin, vaccines, and injections ensure every medicine stays potent and safe till delivery.",
    iconName: "ThermometerSnowflake",
    metric: "24/7",
    metricLabel: "Cool Storage",
  },
  {
    title: "Best Wholesale Rates",
    tagline: "Better Margins for Your Store",
    description: "Get direct wholesale prices and ongoing bonus schemes like 10+1 free, helping your medical store earn healthy retail profits.",
    iconName: "TrendingDown",
    metric: "Best",
    metricLabel: "Wholesale Rates",
  },
  {
    title: "Fast Local Delivery",
    tagline: "Same-Day Supply Across Bhagalpur",
    description: "Regular daily delivery runs across Bhagalpur, Naugachia, Banka, and Kahalgaon so your shop never runs out of essential medicines.",
    iconName: "Truck",
    metric: "Same-Day",
    metricLabel: "Local Delivery",
  },
  {
    title: "Computerized GST Bills",
    tagline: "Easy Accounts & Tax Credit",
    description: "Every order comes with a printed and digital tax invoice showing batch numbers, expiry dates, and HSN codes for hassle-free bookkeeping.",
    iconName: "FileCheck2",
    metric: "100%",
    metricLabel: "GST Invoices",
  },
  {
    title: "20+ Years of Trusted Service",
    tagline: "Personal Help from Santosh Kumar",
    description: "Friendly service, flexible credit terms for verified retailers, and direct WhatsApp support whenever you need urgent medicines.",
    iconName: "Handshake",
    metric: "20+ Yrs",
    metricLabel: "In Business",
  },
];

export const TIMELINE_MILESTONES: TimelineMilestone[] = [
  {
    year: "2004",
    phase: "Established",
    title: "Founded in Bhagalpur",
    description: "Started by Santosh Kumar with Form 20B & 21B drug licenses at Kotwali Chowk, supplying genuine medicines to 30 local chemist shops.",
    achievements: [
      "Obtained Form 20B & 21B wholesale drug licenses",
      "Partnered with leading pharmaceutical companies",
      "Built reputation on genuine medicines and honest pricing",
    ],
  },
  {
    year: "2011",
    phase: "Growth",
    title: "Warehouse & Cold Storage Expansion",
    description: "Expanded our central facility at Kotwali Chowk, added medical refrigerators for vaccines, and started stocking surgical disposables in bulk.",
    achievements: [
      "Expanded stock to over 2,500 everyday formulations",
      "Network grew to over 150 retail medical stores",
      "Started systematic batch-wise stock management (FEFO)",
    ],
  },
  {
    year: "2018",
    phase: "Expansion",
    title: "Direct Stockist for 21+ Top Pharma Brands",
    description: "Secured direct wholesale supply from India's best companies including Alkem, Cipla, Mankind, Dr Reddy, and Abbott.",
    achievements: [
      "Daily delivery routes across Bhagalpur, Naugachia, and Kahalgaon",
      "Added full range of surgical items, Ayurvedic care, and OTC products",
      "Full computerized GST billing and ledger management",
    ],
  },
  {
    year: "Today",
    phase: "Today",
    title: "Serving 200+ Medical Stores & Clinics",
    description: "Providing local pharmacists with easy catalog browsing, fast phone/WhatsApp ordering, transparent wholesale prices, and same-day delivery.",
    achievements: [
      "Over 10,000 active medicines and healthcare supplies",
      "Fast WhatsApp & online order booking with instant bills",
      "Dedicated phone support for local medical shop owners",
    ],
  },
];
